name: Release on Stable

on:
  push:
    branches:
      - stable

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check formatting (go fmt)
        run: |
          out=$(go fmt ./...)
          if [ -n "$out" ]; then
            echo "The following files are not gofmt'ed:" >&2
            echo "$out" >&2
            exit 1
          fi

      - name: Run tests
        run: go test ./...

      - name: Set up QEMU (for cross-compiling)
        uses: docker/setup-qemu-action@v3

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (release on success)
        if: success()
        run: |
          goreleaser release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 